/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package talkathon;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author root
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        txtusername.setBackground(new java.awt.Color(0,0,0,1));
        txtpass.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BodyImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        txtSignup = new javax.swing.JLabel();
        txtForgotPass = new javax.swing.JLabel();
        rememberMe = new javax.swing.JCheckBox();
        txtpass = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background2.setBackground(new java.awt.Color(255, 255, 255));
        Background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setText("Brain");
        Background2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 369, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("WithLess");
        Background2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 369, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        jLabel7.setText("Developed By");
        Background2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 370, -1, -1));

        BodyImg.setIcon(new javax.swing.ImageIcon("C:\\Project Talkathon\\ChattingApp\\src\\talkathon\\login\\BodyImg.png")); // NOI18N
        Background2.add(BodyImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 310, 390));

        getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 414));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Project Talkathon\\ChattingApp\\src\\talkathon\\login\\Logo.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Project Talkathon\\ChattingApp\\src\\talkathon\\login\\PassEyeIcon.png")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 30, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Project Talkathon\\ChattingApp\\src\\talkathon\\login\\UserIcon.png")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 40, 20));
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Don't have account ?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 353, -1, -1));

        loginButton.setBackground(new java.awt.Color(0, 102, 255));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Log In");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, -1, -1));

        txtSignup.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        txtSignup.setForeground(new java.awt.Color(0, 102, 255));
        txtSignup.setText("Sign Up");
        txtSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSignupMouseClicked(evt);
            }
        });
        jPanel1.add(txtSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 371, -1, -1));

        txtForgotPass.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        txtForgotPass.setForeground(new java.awt.Color(255, 255, 255));
        txtForgotPass.setText("Forgot Password ?");
        jPanel1.add(txtForgotPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 312, -1, -1));

        rememberMe.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        rememberMe.setForeground(new java.awt.Color(255, 255, 255));
        rememberMe.setText("Remember me");
        jPanel1.add(rememberMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtpass.setFont(txtpass.getFont());
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtpass.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 220, 21));

        txtusername.setFont(txtusername.getFont());
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtusername.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 21));

        jLabel3.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("_______________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("_______________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        Password.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Username.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username :");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cantarell Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Log In To Your Account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        Welcome.setFont(new java.awt.Font("Cantarell Extra Bold", 1, 18)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Welcome Back");
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Project Talkathon\\ChattingApp\\src\\talkathon\\login\\Background.png")); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 320, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/talkathon","root","77808");
            String sql = "select * from talkathonlogin where Name=? and Password=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, txtusername.getText());
            pst.setString(2, txtpass.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()==true)
            {
                //JOptionPane.showMessageDialog(null, "Username and Password Is Correct");
                peopledata newdata = new peopledata();
        newdata.setVisible(true);
        this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username and Password Doesn't Matched");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void txtSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSignupMouseClicked
        // TODO add your handling code here:
        signup newsign = new signup();
        newsign.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtSignupMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked

    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Background2;
    private javax.swing.JLabel BodyImg;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JCheckBox rememberMe;
    private javax.swing.JLabel txtForgotPass;
    private javax.swing.JLabel txtSignup;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
